### ISSUE TITLE
satuan bahan di data pembelian dan detail tidak ada

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#11]
bang alhamdulillah yang fix nama produk udah berhasil. cuma yang satuan bahan di data pembelian dan detail pembelian jadi gak ada. mungkin karena kemarin benerin nya langsung di laptop saya, maap ya bang udah nyari beda nya masih belum nemu tadinya mau diubah sendiri sekalian belajar tapi belum nemu hehehe. soalnya Salma ga di git pull, di download baruu.

buat harga sama subtotal belum pake format RP, yang ada baru di buku besar

**Comment by oktapascal** [comment]
di PembelianModel sudah ditambahkan ini untuk menampilkan satuan.
`public function getDetail($id)
    {
        $this->db->select('a.id_bahan,nama_bahan,jumlah,satuan,harga,subtotal');
        $this->db->from('bahan a');
        $this->db->join('detail_pembelian b', 'a.id_bahan=b.id_bahan');
        $this->db->where('id_transaksi',$id);
        return $this->db->get()->result_array();
    }`

untuk menambahkan format 'Rp.' sudah diupdate. 
ini di file detail_view di folder pembelian 
`<td>Rp. <?php echo number_format($pb['harga']); ?></td>
<td>Rp. <?php echo number_format($pb['subtotal']); ?></td>` 

dan ini di file lihat_view di folder pembelian
`<td>Rp. <?php echo number_format($ps['total']); ?></td>`

kalo udah di otak-atik disarankan : 
1. hapus dulu semua filenya atau hapus foldernya. 
2. buka folder htdocs di xampp 
3. klik kanan pilih git bash 
4. ketik git clone https://github.com/oktapascal/MoneLab.git
5. klik enter

kalo udah di otak-atik bakal tabrakan kalo pake git pull

**Comment by oktapascal** [comment]
Sudah diupdate dengan issues satuan bahan di data pembelian dan detail tidak ada. menunggu review
