### ISSUE TITLE
satuan dan format RP sebelum simpan pesanan, pembelian, dan produksi

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#12]
yang belum ada satuan bahan: 
-data pesanan dan detail pesanan (kolom jumlah)
-data pembelian (kolom jumlah)

yang belum ada format RP rata kanan :
-Data Pesanan dan Detail Pesanan (kolom harga dan subtotal)
-Data Pembelian sebelum klik Simpan Pembelian (kolom harga dan subtotal)
-Perhitungan Produksi dan Detail Produksi
-Jurnal Umum
-Laporan HPP
- Kartu Harga Pokok Pesanan

udah coba nambahin tapi masih belum berhasil hehe. makasih bang

**Comment by oktapascal** [comment]
Done, waiting review

**Comment by salmazulfa16** [comment]
Pas klik detail pembelian error ya katanya :

**Error Number: 1054

Unknown column 'satuan' in 'field list'

SELECT `a`.`id_kopi`, `nama_kopi`, `jumlah`, `subtotal`, `nama_reseller`, `status`, `satuan` FROM `kopi` `a` JOIN `detail_pesanan` `b` ON `a`.`id_kopi`=`b`.`id_kopi` JOIN `reseller` `c` ON `b`.`id_reseller`=`c`.`id_reseller` WHERE `b`.`id_pesanan` = 'PSN-00001'

Filename: C:/xampp/htdocs/MoneLab/system/database/DB_driver.php

Line Number: 691**

- Satuan masih belum muncul bang di saya aneh ya 
- Untuk Master Bahan setelah dilakukan produksi stok tidak 0

makasih bang

**Comment by oktapascal** [comment]
1. Error di pembelian sudah di perbaiki
2. Satuan di detail pembelian sudah ditambahkan
3. Master bahan setelah produksi setelah di tes berjalan normal (stok berubah menjadi 0)

1. coba hapus dulu foldernya
2. terus buka folder htdocs
3. klik kanan
4. klik git bash 
5. ketik git clone https://github.com/oktapascal/MoneLab.git


Done. waiting review.
