### ISSUE TITLE
Tambahan Revisi di Detail Pembelian ada keterangan pembelian dari pesanan yang mana

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#13]
- Di Detail Pembelian ada keterangan pembelian dari pesanan yang mana

review yang sebelumnya :
- satuan masih belum muncul bang, aneh tapi gapapa kalo di bang okta udah bisa mungkin di akunya bermasalah
- ketika klik detail pesanan muncul error 
**Error Number: 1054

Unknown column 'satuan' in 'field list'

SELECT `a`.`id_kopi`, `nama_kopi`, `jumlah`, `subtotal`, `nama_reseller`, `status`, `satuan` FROM `kopi` `a` JOIN `detail_pesanan` `b` ON `a`.`id_kopi`=`b`.`id_kopi` JOIN `reseller` `c` ON `b`.`id_reseller`=`c`.`id_reseller` WHERE `b`.`id_pesanan` = 'PSN-00001'

Filename: C:/xampp/htdocs/MoneLab/system/database/DB_driver.php

Line Number: 691**

Makasih sebelumnya bang

**Comment by oktapascal** [comment]
Done, waiting review
