### ISSUE TITLE
Mau tanya codingan

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#14]
Udah berhasil bang makasiih 👍 

bang, kalau di tabel Detail Pembelian pengen muncul pembelian dari pesanan yang mana itu gimana caranya ya hehe, soalnya di produksi ada nama kopi sama id kopi dari pesanan yang di produksi..

**Comment by oktapascal** [comment]
Kalo untuk melihat data pesanan di detail pembelian, kamu bisa lihat di file detail_view di folder pembelian. di syntax ini 
`<tr>
<td><?php echo $no; ?></td>
<td><?php echo $pb['id_pesanan']; ?></td>
<td><?php echo $pb['id_bahan']; ?></td>
<td><?php echo $pb['nama_bahan']; ?></td>
<td style="text-align: right"><?php echo $pb['jumlah']; ?> <?php echo $pb['satuan']; ?></td>
<td style="text-align: right">Rp. <?php echo number_format($pb['harga']); ?></td>
<td style="text-align: right">Rp. <?php echo number_format($pb['subtotal']); ?></td>
</tr>`
di baris 25.

datanya diambil dari PembelianModel di function getDetail. codenya kaya gini di baris 21
`public function getDetail($id)
    {
        $this->db->select('a.id_bahan,nama_bahan,jumlah,satuan,harga,subtotal,id_pesanan');
        $this->db->from('bahan a');
        $this->db->join('detail_pembelian b', 'a.id_bahan=b.id_bahan');
        $this->db->where('id_transaksi',$id);
        return $this->db->get()->result_array();
    }`
disitu ada kolom id_pesanan
