### ISSUE TITLE
Revisi Baru Bu Nelsi

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#16]
1. Reseller bisa nambah data yg sama jadi redundancy
2. BTKL itu dihitung perjumlah produk yang dipesan, jadi misal Kopi Robusta BTKL nya Rp 100.000 pesan 10, jadi Rp 100.000x10pcs. Munculkan di Detail Perhitungan Produksi sebelum **Simpan**
3. Perhitungan BOP diubah, jadi :
BOP nya kan ada Mesin, Listrik, Biaya Bahan Penolong
Misal pemeliharaan mesin satu bulan Rp.100.000, trs produk yg diproduksi sebulan nya 100pcs, berarti -Pemeliharaan Mesin = Rp 100.000 perbulan/100pcs = Rp 1000 BOP MESIN
-Listrik = Rp 500.000perbulan/100pcs=  Rp 50.000 BOP LISTRIK
-Biaya Bahan Penolong Dari Pembelian bahan penolong
4. Jurnal Pemakaian BOP nya gak ada, jadi jurnal pemakaian bahan penolong sama BOP beda

Bang, katanya deadline nya Selasa biar bisa sidang Juni...

**Comment by oktapascal** [comment]
Done, waiting review.

kalo mau kodingannya bisa di cek di folder view/produksi file hitung_view sama di folder model/ProduksiModel di function KonfProduksi.

Sumber referensi : https://www.jurnal.id/id/blog/2018-ketahui-cara-menghitung-harga-pokok-pesanan-dengan-benar/
