### ISSUE TITLE
review baru sama nanyaa

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#17]
1. BTKL Di Perhitungan Produksi
- BTKL dijabarkan di perhitungan x produk x 3 orang 
- BTKL di detail produksi beda sama di perhitungan sebelum klik simpan

2. Di Detail Produksi sama di Perhitungan Total Biaya Produksi nya masih salah bang hehe kalau dijumlah...

3. Jurnal BOP yang Sesungguhnya bahan penolong ga dimasukin? Jadi cuma biaya mesin sama listrik?

4. Nominal jurnal selisih BOP itu darimana ya bang?

5. Jurnal Barang jadi
-BTKL di jurnal barang jadi nya belum dikali produk sm 3 orang (ga sesuai nominalnya)
- BOP di jurnal barang jadi pakai yg dibebankan? 

6. Biaya Listrik per produk sama Mesin per produk nya masukin di master data Kopi aja bang sama kayak BTKL, soalnya takutnya ibu mau kayak gitu jadi ntar bisa diubah juga

**Comment by oktapascal** [comment]
1. BTKL Di Perhitungan Produksi :
 - BTKL dijabarkan di perhitungan x produk x 3 orang (Done)
 - BTKL di detail produksi beda sama di perhitungan sebelum klik simpan (Done)

2. Di Detail Produksi sama di Perhitungan Total Biaya Produksi nya masih salah bang hehe kalau dijumlah (Done)  

3. Jurnal BOP yang Sesungguhnya bahan penolong ga dimasukin? Jadi cuma biaya mesin sama 
    listrik? enggak dimasukin karena dia udah di jurnal pas pemakaian bahan bakunya (cek jurnalnya aja) nanti ada jurnal :
BOP yang sesungguhnya xxx
        Persediaan Bahan Penolong xxx

4. Nominal jurnal selisih BOP itu darimana ya bang? dari perbandingan antara BOP yang dibebankan sama BOP yang sesungguhnya. kalo BOP yang dibebankan > BOP yang sesungguhnya  entar jurnalnya :
BOP yang sesungguhnya xxx
    Selisih BOP xxx
kalo BOP yang dibebankan < BOP yang sesungguhnya entar jurnalnya :
Selisih BOP xxx
    BOP yang sesungguhnya xxx
untuk PA kamu BOP yang dibebankan pasti selalu lebih besar karena BOP yang sesungguhnya cuman Listrik, Mesin, sama Bahan penolong aja. (Ini baru asumsi saya aja soalnya dulu ada temen kasusnya kaya gitu, misal kalo ditanya pembimbing atau penguji jawabnya kaya gitu aja tapi kalo pembimbing ngasih saran lain silahkan tulis sarannya di issues). BOP yang dibebankan selalu lebih besar karena ada dasar perhitungan BOP yang rumusnya taksiran bop/taksiran jumlah produksi.

5. Jurnal Barang jadi :
- BTKL di jurnal barang jadi nya belum dikali produk sm 3 orang (ga sesuai nominalnya) (Done)
- BOP di jurnal barang jadi pakai yg dibebankan? Iya pake yang dibebankan karena BOP yang dibebankan itu perkiraan bop sebelum dihitung kembali yang akan menjadi BOP yang sesungguhnya (kalo gak salah yah soalnya pernah ditanya pas sidang haha)

6. Biaya Listrik per produk sama Mesin per produk nya masukin di master data Kopi aja bang sama kayak BTKL, soalnya takutnya ibu mau kayak gitu jadi ntar bisa diubah juga (Done)

Notes : Import database lagi yah soalnya ada nambah kolom

**Comment by salmazulfa16** [comment]
iyaaaa baaangggg makaaasihhhh banyak bang oktaaa!!!
