### ISSUE TITLE
review

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#18]
bang okta 
- biaya produksi nya berarti : BBB + BTKL + BOP (dibebankan)
- Perhitungan yg sekarang : BOP tarif(dibebankan) + biaya penolong
- perhitungan yang seharusnya : BBB + BTKL + BOP tarif saja (ga ditambah biaya penolong soalnya biaya penolong kan BOPs)

**Comment by oktapascal** [comment]
Biaya penolong itu udah pasti masuk BOP tepatnya BOP yang sesungguhnya. Paling kalo gamau ribet, enggak perlu ada BOP yang dibebankan. BOP yang sesungguhnya aja. Jadi entar gak ada jurnal selisih BOP

**Comment by salmazulfa16** [comment]
Ngga bang, maksudnya minta dibetulin :

Di perhitungan biaya produksi aplikasi nya gak ditambahin biaya bahan
penolong, jadi BBB + BTKL + BOP (dari yg tarif aja)

Makasih bang

Pada tanggal Sab, 6 Jun 2020 21:48, Okta Pascal Ibrahim <
notifications@github.com> menulis:

**Comment by oktapascal** [comment]
Kalo saran saya sih jangan, yang ada kamu bisa diskakmat sama penguji kalo BOP cumam dari tarif

**Comment by salmazulfa16** [comment]
Okay bang siappp, makasih banyak🙏🏻

Pada tanggal Sab, 6 Jun 2020 21:56, Okta Pascal Ibrahim <
notifications@github.com> menulis:

**Comment by oktapascal** [comment]
Coba dulu bimbingan sama bu nelsi untuk progress yang ini. Nanti bisa tulis di issues kalo ada perubahan
