### ISSUE TITLE
bertanya codingan

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#19]
1. bang kalau mau lihat BOM pas di klik lihat di table data bom nya pengen ditambahin itu lihat BOM dari kopi yg mana ditambahin apa di view?

2, sama ini masih reset form ketika submit kalau mau lihat bom itu caranya biar ga reset tetep nampil produk yg dipilih gimana? 

makasih sebelumnya...

**Comment by oktapascal** [comment]
1. Iya di file bom_view, nanti di controller BomController di function LihatBom kamu tambahin $index['kopi'] = $kopi; biar data kopinya ke kirim di view. Terus di bom_viewnya tambahin <?php echo $kopi; ?> misal mau tambah disini 
<h3 class="box-title">Data BOM <?php echo $kopi; ?></h3>

2. Bisa di taro di session pas di submit, ini reset karena kamu cuman pake PHP, kalo gamau reset bisa pake ajax javascript

**Comment by salmazulfa16** [comment]
bang tapi malah error sebelum klik lihat yang Lihat BOM, array string gitu error nya, trs pas udah pilih kopi berhasil lihat dan muncul id kopi, tapi pas mau pilih kopi lagi daftar kopi nya gaada hehe

**Comment by oktapascal** [comment]
Iya soalnya itu nilainya belum ada, kalo mau dikasih
```
 <?php if(!empty($kopi)) { ?>
<h3>Data BOM <?php echo $kopi ?>
<?php } ?>
```

**Comment by salmazulfa16** [comment]
<?php if(!empty($kopi)) { ?>
<h3>Data BOM <?php echo $kopi ?>
<?php } ?>

ditambahnya dimana ya bang? setelah controller ditambah $index['kopi'] = $kopi; ??

**Comment by oktapascal** [comment]
di viewnya

**Comment by salmazulfa16** [comment]
udah bang tapi masih error hehe

**Comment by oktapascal** [comment]
Coba download lagi, udah saya perbaiki

**Comment by salmazulfa16** [comment]
Siap bang udah makasih banyak

Pada tanggal Sen, 8 Jun 2020 09:18, Okta Pascal Ibrahim <
notifications@github.com> menulis:

**Comment by salmazulfa16** [comment]
Bang mau tanya lagi hehe

Kalau mau tambahin kop laporan gimana caranya ya hehehe kayak di jurnal
buku besar sm laporan hpp?

Pada tanggal Sen, 8 Jun 2020 10:30, Salma Zulfa Nabilah <
salmazulfanabilah16@gmail.com> menulis:

**Comment by oktapascal** [comment]
Bisa pakai kaya gini 
```
<div class="col-md-5 col-lg-5">
<h3 class="box-title">Buku Besar</h3>
</div>
```
col itu maksudnya jumlah kolom yang dibutuhkan bisa disesuaikan sesuai kebutuhan

**Comment by salmazulfa16** [comment]
Kalau yg lengkap gitu bang sama nama perusahaan sama periode jugaa hehehe
biar ditengah juga

Pada tanggal Sen, 8 Jun 2020 18:28, Okta Pascal Ibrahim <
notifications@github.com> menulis:

**Comment by oktapascal** [comment]
Bisa kaya gini misal mau nambah header nama perusahaan dan periode di tabel jurnal
```
<thead>
<tr>
<th colspan="6">Periode 2019</th>
</tr>
<tr>
<th colspan="6">Nama perusahaan</th>
</tr>
<tr>
<th>Tanggal</th>
<th>No Akun</th>
<th>Nama Akun</th>
<th>Reff</th>
<th>Debet</th>
<th>Kredit</th>
</tr>
</thead>
```

**Comment by salmazulfa16** [comment]
malah berantakan bang haha

**Comment by oktapascal** [comment]
Udah ditambahin, silahkan di cek kalo mau tau cara tambah header di jurnal dan buku besarnya
