### ISSUE TITLE
Tambahan dari Ibu...

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#21]
1. Detail perhitungan biaya produksi nya bisa dilihat lagi di detail produksi, ada button untuk lihat lagi perhitungan produksinya bang

2. Untuk **1 ID pesanan** seharusnya hanya untuk **satu nama reseller** tapi bisa pesan lebih dari satu jenis produk?

3. Inputan buat nominal atau angka validasi nya belum kalau input (-1000) atau 0 masih valid

4. Untuk **total biaya produksi** nya dibagi lagi jumlah produk yg dipesan, jadi HPP per satuan produknya ketahuan. Misal total biaya produksi 1.500.000/30 pcs karena pesan 30pcs. Jadi, HPP satuan produknya sebesar Rp 50.000

5. Harga Jual di Kartu Harga Pokok Pesanan tidak usah ada

Makasih sebelumnya bang....

**Comment by oktapascal** [comment]
1. Detail perhitungan biaya produksi nya bisa dilihat lagi di detail produksi, ada button untuk lihat lagi perhitungan produksinya bang

2. [v] Untuk **1 ID pesanan** seharusnya hanya untuk **satu nama reseller** tapi bisa pesan lebih dari satu jenis produk?

3. Inputan buat nominal atau angka validasi nya belum kalau input (-1000) atau 0 masih valid

4. Untuk **total biaya produksi** nya dibagi lagi jumlah produk yg dipesan, jadi HPP per satuan produknya ketahuan. Misal total biaya produksi 1.500.000/30 pcs karena pesan 30pcs. Jadi, HPP satuan produknya sebesar Rp 50.000

5. Harga Jual di Kartu Harga Pokok Pesanan tidak usah ada

Makasih sebelumnya bang....

**Comment by oktapascal** [comment]
Silahkan cek
