### ISSUE TITLE
Pehitungan Produksi total **Biaya Bahan Penolong**

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#22]
Bang punten...baru dicoba lagi kalau pesan 2 Jenis Produk dalam 1 ID Pesanan.

**total biaya bahan penolong** nya kalau dalam **1 ID Pesanan pesan 2 jenis produk** terus kan dilakukan pembelian nya. Total biaya bahan penolong nya kan  beda tiap produk, misal :
- Total Bahan Penolong di produk 1 : 70.000
- Total Bahan Penolong di produk 2 : 130.000

yang seharusnya :
-kalau produksi produk pertama Biaya Bahan Penolongnya sebesar Rp 70.000, dan
-kalau produksi produk kedua Biaya Bahan Penolongnya sebesar Rp 130.000

**Ini di perhitungan produksi jenis produk pertama dan kedua biaya penolong nya tuh jumlahnya sama - sama Rp 200.000 (70.000+130.000)**

Jadi **total biaya bahan penolong** di produksi nya juga ngga disatuin dari pembelian biaya bahan penolong produk 1 sm produk 2, karena produksi nya kan satu satu...
nah ini **biaya bahan penolong nya masih ngetotal dari jumlah pembelian bahan penolong 2 jenis produk dalam **1 ID pesanan**

Makasih bang

**Comment by oktapascal** [comment]
Done. jangan lupa import baru databasenya karena ada penambahan kolom di detail_pembelian

**Comment by salmazulfa16** [comment]
bang pas produksi biaya penolong nya jadi 0

**Comment by oktapascal** [comment]
Kamu ngapain ini ? kemaren lancar aja soalnya

**Comment by salmazulfa16** [comment]
ini coba yg baru bang, yg kalau 1 Id pesanan pesen 2 produk yg beda, trs pembelian bahan penolongnya jg kan harusnya beda pas ngitung produksi satu2. ini mah jadi ngetotal biaya bahan penolongnya dari pembelian produk 1 sama produk 2

**Comment by oktapascal** [comment]
Saya udah coba, lancar lancar aja kok. biaya bahan penolongnya udah sesuai per produknya

**Comment by salmazulfa16** [comment]
iyaa udah di download ulang bang udah bisa lagii, makasiii

**Comment by oktapascal** [comment]
Jangan diotak-atik dulu. Soalnya ini udah mendekati sidang. Saya gamau otak atik PA kamu mulai hari ini sampe sidang soalnya. Nanti kamu yang rugi. Kalo pembimbung minta yang masih masuk akal baru saya mau otak atik, tapi kalo sekiranya bakal mempengaruhi yang lain itu dimasukim buat revisi setelah sidang aja.

**Comment by salmazulfa16** [comment]
iya siap bang

mau tanya lagi, kalau mau menambahkan nama kopi di detail pembelian gimana ya bang hehe

**Comment by oktapascal** [comment]
1. Buka file PembelianModel
2. Cari function getDetail
3. Ganti kodingan yang di dalam getDetail jadi seperti ini :
```
$this->db->select('a.id_bahan,nama_bahan,jumlah,satuan,harga,subtotal,id_pesanan,nama_kopi');
$this->db->from('bahan a');
$this->db->join('detail_pembelian b', 'a.id_bahan=b.id_bahan');
$this->db->join('kopi c', 'b.id_kopi=c.id_kopi');
$this->db->where('id_transaksi',$id);
return $this->db->get()->result_array();
```
4. Buka file detail_view di folder pembelian
5. Tambahkan syntax ini setelah kolom id_pesanan :
```
<td><?php echo $pb['nama_kopi']; ?></td>
```
