### ISSUE TITLE
mau tanya codingan buku besar

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#23]
`<?php`
				if(!empty($saldo['selisih']))
				{
				echo "
					<tr>
						<td>0000-00-00</td>
						<td>Saldo Awal</td>
						<td></td>
						<td></td>
						<td align = 'right'>".format_rp(abs($saldo['selisih']))."</td>
					</tr>
				";
				$saldo_awal = $saldo['selisih'];
				}
				else{
				echo "
					<tr>
						<td>0000-00-00</td>
						<td>Saldo Awal</td>
						<td></td>
						<td></td>
						<td align = 'right'>".format_rp(0)."</td>
					</tr>
				";
				$saldo_awal = 0;
				}
				foreach($buku as $data){
					echo "
						<tr>
							<td>".$data['tanggal']."</td>
							<td>".$data['nama_akun']."</td>
						";
					if($data['posisi_db_cr'] == 'D'){
						//if($dataakun['header_akun'] == d or $dataakun['header_akun'] == 5 or $dataakun['header_akun'] == 6){
		                if($data['header_akun'] == 1 || $data['header_akun'] == 5 || $data['header_akun'] == 6)
						{
							$saldo_awal = $saldo_awal + $data['nominal'];
						}
						else{
							$saldo_awal = $saldo_awal - $data['nominal'];	
						}
						echo "
							<td align = 'right'>".format_rp($data['nominal'])."</td>
							<td></td>
							<td align = 'right'>".format_rp(abs($saldo_awal))."</td>
						</tr>
						";
					}else{
						if($data['header_akun'] == 1 || $data['header_akun'] == 5 || $data['header_akun'] == 6)
						{
						$saldo_awal = $saldo_awal - $data['nominal'];
						}
						else{
						$saldo_awal = $saldo_awal + $data['nominal'];	
						}
						echo "
							<td></td>
							<td align = 'right'>".format_rp($data['nominal'])."</td>
							<td align = 'right'>".format_rp(abs($saldo_awal))."</td>
						</tr>
						";
					}
				}
				echo "
					<tr>
						<td>0000-00-00</td>
						<td>Saldo Akhir</td>
						<td></td>
						<td></td>
						<td align = 'right'>".format_rp(abs($saldo_awal))."</td>
					</tr>
				";
			?>
		</table>
            <?php } ?>`

bang kalau ada waktu minta tolong dijelasin ya hehe yg penting2 nya aja dari script itu. di bukbes_view line 49-123

makasih sebelumnya

**Comment by oktapascal** [comment]
- Melakukan pengecekan jika variabel $saldo['selisih'] nilainya kosong maka nilai saldo awalnya 0.
- format_rp itu helper untuk konversi ke format rupiah
- Jika posisi jurnalnya di Debet kemudian jika header akunnya 1 atau 5 atau 6, maka saldo_awal akan ditambah dengan nominal yang di jurnal. dan datanya akan ada di posisi kolom debet.
-abs itu function di php untuk membulatkan bilangan negatif ke positif. kalo mau dibikin negatif tinggal hapus aja function abs()

**Comment by salmazulfa16** [comment]
Kalau mau munculin *harga satuan* di detail pesanan gimana bang? Sebelum
kolom subtotal, jadi ngga langsung subtotal. Takut salah kalau seandainya
disuruh tambahin heheh

Pada tanggal Sen, 15 Jun 2020 14:14, Okta Pascal Ibrahim <
notifications@github.com> menulis:

**Comment by oktapascal** [comment]
Cek di model dulu ada kolom untuk data harga satuan atau enggak, kalo gak gak ada bisa ditambahin di modelnya. Nanti di view detailnya tinggal panggil indexnya. Caranya sama nulis buat subtotal cuman nanti diganti harga_satuan misalnya $bl['harga_satuan']
