### ISSUE TITLE
Revisi Sidang

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#24]
1. Tambahkan Jurnal BTKL
**Jurnal nya : BDP-BTKL                       xxxx
                              Gaji dan upah              xxxx**

2. Menu setoran modal dan mutasi saldo (perbulan dan pertahun)

3. Tambahkan kolom nomor rekening pada buku besar

4. Laporan HPP dilengkapi kayak biaya angkut pembelian, retur, potongan pembelian, dan diskon pembelian walaupun biaya angkut, retur, potongan, dan diskon 0 juga diadain aja komponen itu.
(kayak laporan hpp yang lengkap)

5. Di master data kopi udah ada harga jual nya, jadi pas transaksi pesanan gausah diinput lagi harga nya. 

List harga - harga kopi nya:

1. Signature Taste Robusta : Rp 58.000
2. Signature Taste Arabica: Rp 58.000
3. Signature Taste Excellsa: Rp 60.000
4. Premium Taste Robusta : Rp 50.000
5. Premium Taste Arabica: Rp 50.000
6. Premium Taste Excellsa: Rp 52.000
7. Honeynitro Arabica Coffee : Rp 62.000
8. Honeynitro Robusta Coffee : Rp 62.000
9. Tolu Batak Wet Hulled : Rp 64.500
10. Brown Bean Arabica Nutural Process : Rp 68.000
11. Brown Bean Robusta Nutural Process : Rp 68.000

Bang database nya baru, aku kirim ke teh rike ya soalnya gangerti kalau kirim disini, soalnya BOM nya pada baru hehe

**Comment by oktapascal** [comment]
1. [X] Tambahkan Jurnal BTKL
**Jurnal nya : BDP-BTKL                       xxxx
                              Gaji dan upah              xxxx**

2. [X] Menu setoran modal dan mutasi saldo (perbulan dan pertahun)

3. [X] Tambahkan kolom nomor rekening pada buku besar

4. [X] Laporan HPP dilengkapi kayak biaya angkut pembelian, retur, potongan pembelian, dan diskon pembelian walaupun biaya angkut, retur, potongan, dan diskon 0 juga diadain aja komponen itu.
(kayak laporan hpp yang lengkap)

5. [X] Di master data kopi udah ada harga jual nya, jadi pas transaksi pesanan gausah diinput lagi harga nya. 

List harga - harga kopi nya:

1. Signature Taste Robusta : Rp 58.000
2. Signature Taste Arabica: Rp 58.000
3. Signature Taste Excellsa: Rp 60.000
4. Premium Taste Robusta : Rp 50.000
5. Premium Taste Arabica: Rp 50.000
6. Premium Taste Excellsa: Rp 52.000
7. Honeynitro Arabica Coffee : Rp 62.000
8. Honeynitro Robusta Coffee : Rp 62.000
9. Tolu Batak Wet Hulled : Rp 64.500
10. Brown Bean Arabica Nutural Process : Rp 68.000
11. Brown Bean Robusta Nutural Process : Rp 68.000

Bang database nya baru, aku kirim ke teh rike ya soalnya gangerti kalau kirim disini, soalnya BOM nya pada baru hehe

**Comment by oktapascal** [comment]
Sudah dicoba dan berhasil, silahkan dicoba kembaliSudah dicoba dan berhasil, silahkan dicoba kembali
