### ISSUE TITLE
Revisi format buku besar

### ISSUE THREAD

**Issue by salmazulfa16** [oktapascal/MoneLab#25]
assalamualaikum bang..
salma barusan abis revisi sm bu reni katanya masih ada yg harus diperbaiki format Buku Besar nya sesuai buku referensi salma.
buku referensi nya udah salma kirim ke teh rike lewat WA..
sebenernya salma ditungguin sama bu renny sekarang

makasih banyak bang

**Comment by oktapascal** [comment]
Udah ditambah cek lagi coba
